class User(models.Model):
    username = models.CharField(primary_key=True, unique=True, max_length=30)
    password = models.CharField(max_length=50, blank=False, null=False)
    first_name = models.CharField(max_length=30, blank=False, null = False)
    middle_name = models.CharField(max_length=30, blank=False, null = False)
    last_name = models.CharField(max_length=30, blank=False, null=False)
    last_auth = models.CharField(max_length=256, blank=False, null = False, unique = True)
    region = models.CharField(max_length=50, blank=False, null=False)
    nation = models.CharField(max_length=50, blank=False, null=False)
    city = models.CharField(max_length=50, blank=False, null=False)
    biography = models.CharField(max_length=300, blank=False, null=False)
    resume = models.FilePathField(null=False, blank=False)
    portfoliourl = models.URLField(null=True, blank=True)
    phone_number = models.CharField(max_length=30, null=False, blank=False)
    email = models.EmailField(max_length=50, null=False, blank=False)
    sq1 = models.CharField(max_length=20, blank=False, null=False)
    sq2 = models.CharField(max_length=20, blank=False, null=False)
    sq1a = models.CharField(max_length=20, blank=False, null=False)
    sq2a = models.CharField(max_length=20, blank=False, null=False)
